### ISSUE TITLE
varnish stats over tcp

### ISSUE THREAD

**Issue by glensc** [jonnenauha/prometheus_varnish_exporter#11]
hi,

please consider adding tcp interface so the stats could be pulled over xinetd or similar.

i've used this technique in cacti template that i now maintain:
https://github.com/glensc/cacti-template-varnish

**Comment by jonnenauha** [comment]
Yeah, no need to lock this down to prometheus only, even if its the repo name.

So what are you interested in exactly. Your code seems to remote execute the varnishstat now https://github.com/glensc/cacti-template-varnish/blob/master/get_varnish_stats.py#L155-L168?

You would like to replace that with connecting to my exporter with TCP. Do you want it to just echo the original varnishstat stdout lines, or my processed, a bit more refined metrics with labels etc.?

Should my server disconnect after sending all data from the scrape or keep it open?

**Comment by glensc** [comment]
@jonnenauha: read that project README. i want to run exporter on nodeX, while varnish instance(s) run elsewhere. the stats could be grabbed over tcp like the cacti-template-varnish project does.

i have not tested this project yet because your readme says i must run the program on varnish node.

regarding keepalive. idea seems nice, but it may largely depend what the remote side proxy supports.

**Comment by glensc** [comment]
and no, i do not want cacti template to talk to your exporter. i gave you just example how some other project grabs varnish stats remotely for varnish >= 3.
