### ISSUE TITLE
Varnish Grafana dashboard.

### ISSUE THREAD

**Issue by anmoljagetia** [jonnenauha/prometheus_varnish_exporter#17]
I like your varnish dashboard. Would you be willing to share it with the community? I think it would serve as a good starting point in trying to setup and use your plugin.

Thanks.

**Comment by jonnenauha** [comment]
Yes, I have to cleanup what I'm currently using so it works for all setups. It is currently templated over a custom variable/label that would be hard to explain. Best to just remove the templating before I commit it here.

I try to get to this at some point.

**Comment by rabun788** [comment]
+1  Great work, would love the dashboard json!

**Comment by jonnenauha** [comment]
@anmoljagetia @rabun788 sorry guys this took a bit longer than expected, not that much free time atm :)

I have created a new dashboard with more features than the old screenshot shows. I really tried to digg into prometheys features and make it show a lot of useful info. I also uses the new releases new up metrics per backend. So if you want all out of it you should update to the latest release here and probably latest Grafana while you are at it.

You can find the dashboards from now on at each release as a archive or just download from the repo as is, more info in the readme.

**Comment by IntiGabriel** [comment]
Thanks. Very nice Dashboard!

**Comment by anmoljagetia** [comment]
@jonnenauha Thanks a lot. This will help everyone on the lookout for some nice Varnish monitoring. Cheers, and stay awesome :)
