### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by pablolibo** [jonnenauha/prometheus_varnish_exporter#2]
Hi, Thanks for the project is amazing!

Can you share your dashboard? 

Thanks

**Comment by jonnenauha** [comment]
Thanks, I had no idea someone was using it. I sure am, but this is nice to hear :)

Here is a gist for the dashboard in the readme screenshot with a few improvements I've done after the capture https://gist.github.com/jonnenauha/afd05ccea12c6aaf7a02f70dca2890b7 

I do think this might not be that useful as is, as I'm using a `$cluster` grafana variable to have each varnish instance we run its own dashboard. I believe without the variable and the labels being in place, this board won't show you anything.

But, you can edit the queries before/after import, just removing the query labels, for example

```
irate(varnish_main_cache_hit{frontend_for=\"$cluster\"}[30s]) / irate(varnish_main_client_req{frontend_for=\"$cluster\"}[30s])
// to
irate(varnish_main_cache_hit{}[30s]) / irate(varnish_main_client_req{}[30s])
```

You could basically try a simple search and replace of `frontend_for=\"$cluster\"` to an empty string.

If you do end up cleaning it up, or just making your own dashboard it would be cool if you send it to me, I could start adding dashboard configs to the repo for everyone to utilize. I might have to cleanup my config and do the same when I have time.

Let me know how it goes.

**Comment by pablolibo** [comment]
Hey Jonne, Yes, we are using your code :-P

I don't understand where to get the variable: `frontend_for` from prometheus I have the next variable: varnish_main_cache_hit{instance="varnish.prometheus.myserver:9131",job="node"} and I don't found the `frontend_for` variable. Where can I get it?

I've been using without variables like `{}` and it works perfect, but it is not scalable for dashboard.

Your repository is recommended from the official website prometheus and more site. Good job!
It is a good idea that the next commit add your dashboard
Thanks!

**Comment by jonnenauha** [comment]
The `frontend_for` is my custom label that I attach to each varnish instance I run. If you already have a `instance` label on each, you can just replace all `frontend_for` in my dashboard with `instance`. I'm not 100% sure if this is unique per server, or something automatic by the domain? Cant remember.

Then in grafana you can create the custom template properties in the settings. Once you define them, you can use them in queries.

![image](https://cloud.githubusercontent.com/assets/157519/16592232/58a9cd40-42e8-11e6-8bd0-3d3ebe44e9df.png)

For you the values of the `$cluster` template would be comma separated values with all your instance names from prometheus config like `varnish.prometheus.myserver:9131`.

Then you make queries with `varnish_main_cache_hit{instance=\"$cluster\"}[30s])`. This is just to illustrate the point, you can name "cluster" to whatever you want.

Hope that helps.

**Comment by dmizyk** [comment]
Updated dashboard with auto generated list of vanrinsh nodes  (without editing templates),maybe it will be useful for someone.
![image](https://cloud.githubusercontent.com/assets/15911918/25293928/9440ad24-26e5-11e7-981e-ee9015326aae.png)
[varnish.zip](https://github.com/jonnenauha/prometheus_varnish_exporter/files/948175/varnish.json.zip)

**Comment by jonnenauha** [comment]
@dmizyk can I commit this into the repo under `/dashboards` folder? Do you want some kind of attribution somewhere?

**Comment by dmizyk** [comment]
Yes, of course. No additional attribution needed. Thank you for your
project.
