### ISSUE TITLE
Add SHA256 checksums to releases

### ISSUE THREAD

**Issue by sevenval-admins** [jonnenauha/prometheus_varnish_exporter#26]
Would it be possible to add a ‘sha256sums.txt' or similar to future releases?

Examples:
https://github.com/prometheus/prometheus/releases
https://github.com/prometheus/haproxy_exporter

Thanks a lot in advance!

**Comment by jonnenauha** [comment]
Implemented and shipped in release 1.4. Thanks for the feature request.
