### ISSUE TITLE
dashes in vcl names result in no token found

### ISSUE THREAD

**Issue by trondiz** [jonnenauha/prometheus_varnish_exporter#27]
* **Varnish** `5.2`
* **prometheus_varnish_exporter** `1.2.1` (Debian Stretch)

------------------

https://github.com/prometheus/prometheus/issues/3154

I have not tested latest version of the exporter.

**Comment by jonnenauha** [comment]
The VCL name is not actually part of the metric name, what that issue seems to discuss. The name is a label in the metric. I don't remember or see anything in changelog that would have changed this. I believe they have been labels from the beginning.

I did look at the code and I don't replace `-` with `_`, but having dashes in the part of the metric name is not something varnish seems to do. The VCL name is a postfix on the varnish metric name, that gets parsed into the prometheus metric labels.

```
varnish_backend_bereq_bodybytes{backend="eu2",server="unknown"} 0
varnish_backend_bereq_bodybytes{backend="one-two-test",server="unknown"} 0
```

Have you tries recently with a newer prometheus and this exporter if this is still an issue?

**Comment by trondiz** [comment]
I retested to see which metrics get the dash and it looks like its exposed in the backend metrics in varnish:
`varnishadm vcl.load test-dash /etc/varnish/default.vcl`

```
VBE.test-dash.server1.pipe_out                                 0         0.00 Piped bytes to backend            
VBE.test-dash.server1.pipe_in                                  0         0.00 Piped bytes from backend          
VBE.test-dash.server1.req                                      0         0.00 Backend requests sent             
```
Which is turned into this when i fetch `/metrics` on the exporter:
```varnish_backend_test-dash_server1_pipe_in 0
varnish_backend_test-dash_server1_pipe_out 0
varnish_backend_test-dash_server1_req 0
```
I run prometheus 2.2.1 and the varnish_exporter (1.2.1) that is in Debian Stretch. So I'd need to build a newer version to retest. I have worked around it for now by avoiding dashes when loading a new vcl.

**Comment by jonnenauha** [comment]
I had not used the admin tool to (re)load VCLs before. Seems you can give it a config name that is then present in the varnish metric names.

However the current exporter and Varnish 6.0.0 exports these. The varnish format looks to be the same, so it has not changed formatting.

```
# varnish
VBE.test-dash.one-two-test.pipe_out
VBE.test-dash.one-two-test.req
# exporter
varnish_backend_pipe_out{backend="one-two-test",server="unknown"}
varnish_backend_req{backend="one-two-test",server="unknown"}
```

I jumped to `1.2` tag (I don't have 1.2.1, must be a extra version in the debian packaging side?) and it is indeed doing the formatting you are experiencing

```
varnish_backend_test-dash_one-two-test_pipe_out
```

So this issue has been already fixed, how I understand this now. Please update to the latest version if you can. You did have a good work around for 1.2 though. You should be able to run the pre compiled version for linux as is on Debian https://github.com/jonnenauha/prometheus_varnish_exporter/releases/download/1.4/prometheus_varnish_exporter-1.4.linux-amd64.tar.gz (It's just a static go binary, no system deps etc.)

**Comment by jonnenauha** [comment]
I'm closing this for now. Open it again if you still have problems, thanks!
