### ISSUE TITLE
Add support for varnish 5 with varnish_backend_up and possibly varnish_backend_down

### ISSUE THREAD

**Issue by paladox** [jonnenauha/prometheus_varnish_exporter#29]
* **Varnish** `fill_version` 5
* **prometheus_varnish_exporter** `fill_version` stretch

------------------

Message...

Hi, when using this we are seeing a 0 for varnish_backend_up. Most likly due to varnish 5 changes to backend.

please could support for varnish 5 be added?

**Comment by jonnenauha** [comment]
from readme

> I have personally tested the following versions of Varnish to work 5.2, 5.1.2, 4.1.1, 4.1.0, 4.0.3 and 3.0.5

Are you sure you have health check on the backend server lines. I believe all show "down" if those are not enabled. Are you running the latest version of this exporter?

**Comment by paladox** [comment]
Works now. Thanks.
