### ISSUE TITLE
Add cross platform building

### ISSUE THREAD

**Issue by zoidbergwill** [jonnenauha/prometheus_varnish_exporter#3]
Similar to [this PR](https://github.com/prometheus/prometheus/pull/1556) using [promu](https://github.com/prometheus/promu)

**Comment by jonnenauha** [comment]
I haven't yet done anything "full docker" at this point. There was a previous PR that does cross plat builds, the .sh is in the root, but it looks to be using some extra tools (a suppose bit like promu).

With +1.6 go the script really can be quite simple, so I can just upload binaries here. But for some it might be nice to have the ready made docker image as well.

Here is the build script I wrote for another project https://github.com/jonnenauha/obj-simplify/blob/master/build.sh 

I'll try to look into promu when I have time!

**Comment by zoidbergwill** [comment]
I just saw some people talking about Prometheus using promu on Twitter, and then had a look around in their repo and it looks very neat.

I'd happily do it when I get a chance.

Having a Docker image would be great, and an easy to use list of binaries with each release that can be easily added to an existing Dockerfile.

**Comment by jonnenauha** [comment]
I have updated build scripts for easy releases. I did not end up using promu and did not do any docker stuff.

The 1.0 release I just made has binary downloads for many platforms. https://github.com/jonnenauha/prometheus_varnish_exporter/releases
