### ISSUE TITLE
Script to connect to docker varnish instance

### ISSUE THREAD

**Issue by if-kyle** [jonnenauha/prometheus_varnish_exporter#30]
* **Varnish** `fill_version`
* **prometheus_varnish_exporter** `fill_version`

------------------

Thought I would share, a simple one liner to put on the linux host to fake out prometheus_varnish_exporter into really connecting to the docker container of varnish.  This is gathering stats correctly for me.

cat /usr/local/bin/varnishstat

```
#!/bin/bash
# this is used to fool prometheus_varnish_exporter into getting the info from inside a varnish docker container
sudo docker exec -t varnish sh -c "varnishstat $@"
```

This assumes the varnish container name is "varnish"

**Comment by jonnenauha** [comment]
This looks like a simple enough solution. I can do the exec still in golang. Need to add `-docker-container-name`. If that is defined then I run the command you provided.

I don't think this still solves the problem of running both varnish and this exporter in separate containers. But it's a step in the right direction.

**Comment by if-kyle** [comment]
Yes, container name var would be needed.  I do have an issue where the stats gatherer starts to fail to gather stats, yet I can still run the varnishstat command.  Restarting the golang app makes it start working again.  Unsure if this is related to the docker  exec hack or something else.  This happens at random intervals of time.

**Comment by jonnenauha** [comment]
Alright done https://github.com/jonnenauha/prometheus_varnish_exporter/commit/4d2c3829381bbebb6bf5d9ce1cb81196981a378d

@if-kyle  as you are seemingly running this setup, any change you could test this? If it looks good I could make a release.

**Comment by if-kyle** [comment]
So I am happy to test, but am very new to golang.  

I git checkout prometheus_varnish_exporter to my home dir, cd in and tried to do a go install and got

go install: no install location for directory /home/centos/prometheus_varnish_exporter outside GOPATH
	For more details see: 'go help gopath'

**Comment by if-kyle** [comment]
Thanks for the guide, I was able to build.

Testing, it all works with my docker setup. Thanks!

**Comment by jonnenauha** [comment]
Thanks for trying it out. I made 1.4.1 release now with this and your fixes in.

Here if you want to grab the official one, but its exactly the same as your own built binary. There is no magic in go builds for "releases" :) https://github.com/jonnenauha/prometheus_varnish_exporter/releases/tag/1.4.1
