### ISSUE TITLE
Dashboard not working correctly with Prometheus 2.x

### ISSUE THREAD

**Issue by morsik** [jonnenauha/prometheus_varnish_exporter#31]
* **Prometheus** `2.x`

Some graphs are non-working in Prometheus 2.x. For example function `count_scalar` [was removed](https://www.robustperception.io/functions-to-avoid/) along with others.

![screencapture-185-69-192-76-3000-d-n_ks5ndmk-varnish-2018-06-29-13_16_51](https://user-images.githubusercontent.com/783794/42089695-bb90f9b0-7b9e-11e8-9068-d37c1e0aca69.png)

**Comment by jonnenauha** [comment]
Hmm, any change you could try to figure out what would work instead? I don't have prometheus 2 atm in prod where varnish would be running to test this. Probably something quite simple, but am not an expert in building prom/grafana queries. You can send a PR or just paste me the fixed query here if you want to out.

**Comment by morsik** [comment]
Sorry, I'm very new to Prometheus (just trying it out), and new to Varnish. Just wanted to try out your exporter and found incompatibility ;)
What what I see some functions needs to be changed, but as I said - I'm not Prometheus nor Varnish expert - so don't really know what should be what exactly.
