### ISSUE TITLE
varnishstat from multiple instances

### ISSUE THREAD

**Issue by m8t** [jonnenauha/prometheus_varnish_exporter#44]
* **Varnish** `4.1`
* **prometheus_varnish_exporter** `1.4.1`

------------------

I have two varnish instances running on the same server, and it would be convenient to varnishstat on both instances with the same varnish_exporter process.

**Comment by jonnenauha** [comment]
I don't think this is a common enough use case to rework the code to do this. From my understanding this would involve doing multiple `varnishstat` calls with different `-n` values. You can already pass this to the exporter process to select the instance.
