### ISSUE TITLE
Errors after reloading VCL

### ISSUE THREAD

**Issue by jangrewe** [jonnenauha/prometheus_varnish_exporter#5]
For some reason the exporter recently stopped working after reloading the VCL. The /metrics route now shows loads of these:

```
An error has occurred during metrics collection:

166 error(s) occurred:
* collected metric varnish_backend_beresp_hdrbytes label:<name:"id" value:"boot.bucky" > gauge:<value:43674 >  has label dimensions inconsistent with previously collected metrics in the same metric family
* collected metric varnish_backend_pipe_hdrbytes label:<name:"id" value:"boot.api_gateway_10_1_13_36" > gauge:<value:0 >  has label dimensions inconsistent with previously collected metrics in the same metric family
* collected metric varnish_backend_pipe_in label:<name:"id" value:"boot.frontend_v2_10_1_24_225" > gauge:<value:0 >  has label dimensions inconsistent with previously collected metrics in the same metric family
* collected metric varnish_backend_req label:<name:"backend" value:"frontend_v2_10_1_13_36" > label:<name:"server" value:"43793fc1-9a46-4e0e-8fce-6ceb32582143" > gauge:<value:6 >  has label dimensions inconsistent with previously collected metrics in the same metric family
```

**Comment by jonnenauha** [comment]
Hmm, this is strange as the metrics are not updated, but always created from scratch. Are you using the 1.0 version?

The descs are cached but the values are created on the spot https://github.com/jonnenauha/prometheus_varnish_exporter/blob/master/varnish.go#L98-L111

Did a restart of `prometheus_varnish_exporter` fix this or did it go away over time?

Did the VLC reload remove/add backends?

**Comment by jonnenauha** [comment]
Did those errors print in the /metrics http response or in the servers terminal?

**Comment by jonnenauha** [comment]
What version of varnish do you have? I have not yet tested against 5.x.

**Comment by filippog** [comment]
We (Wikimedia Foundation) have experienced something similar too with Varnish 4 (tracked in https://phabricator.wikimedia.org/T150479) though AFAICT it recovered by itself. I've also opened #8 for a possibly related issue WRT backend identity.

**Comment by jonnenauha** [comment]
I believe I've found the place where this is printed https://github.com/prometheus/client_golang/blob/3fb8ace93bc4ccddea55af62320c2fd109252880/prometheus/registry.go#L704-L707

Still investigating, commenting on the other issue some more.
