### ISSUE TITLE
Varnish (git master) moves all counters into "counters" section.

### ISSUE THREAD

**Issue by simonvik** [jonnenauha/prometheus_varnish_exporter#61]
* **Varnish** `git master`
* **prometheus_varnish_exporter** `git master`

------------------

In https://github.com/varnishcache/varnish-cache/commit/4b4411d2e877ceb2d5b1fdae9a7481b075153a73#diff-bbe6d70e6966a29efce2e8eabe500613 varnish moves all counters into a "counters" section so it changes from : 

```
{
  "timestamp": "2020-06-15T06:05:22",
  "MGT.uptime": {
```

to 
```
{
  "version": 1,
  "timestamp": "2020-06-15T06:07:31",
  "counters": {
    "MGT.uptime": {
```

**Comment by jonnenauha** [comment]
Fixed #64
