### ISSUE TITLE
Varnish scrape failed

### ISSUE THREAD

**Issue by CPC954** [jonnenauha/prometheus_varnish_exporter#62]
* **Varnish** `6.0.6`
* **prometheus_varnish_exporter** `v1.5.2`

------------------

Giving error:

Jun 17 11:45:01 varnish-a1 prometheus_varnish_exporter: Could not get hold of varnishd, is it running?
Jun 17 11:45:01 varnish-a1 prometheus_varnish_exporter: 2020/06/17 11:45:01 [ERROR] Startup test: varnishstat scrape failed: exit status 1

**Comment by lipov3cz3k** [comment]
When varnish runs as `vcache` user (default in systemd) this error occurs. Hot fix is to run prometheus-varnish-exporter service as same user instead of prometheus
```
/lib/systemd/system/prometheus-varnish-exporter.service
...
User=vcache
....
```

**Comment by lipov3cz3k** [comment]
If you run debian and use `prometheus-varnish-exporter` deb package, just add `prometheus` user to `varnish` group

```bash
usermod -G varnish -a prometheus
```

**Comment by jonnenauha** [comment]
Resolve what user varnishd is running as. First column of the results. `ps -ef | grep varnishd`.

Added link to this issue to README, seems this is fairly frequent problem.
