### ISSUE TITLE
Support for Varnish 6.5

### ISSUE THREAD

**Issue by ronaldploeger** [jonnenauha/prometheus_varnish_exporter#65]
* **Varnish** `6.5`
* **prometheus_varnish_exporter** `1.5.2`

------------------

It would be great to get support for Varnish 6.5 ...
... and there is already a PR: https://github.com/jonnenauha/prometheus_varnish_exporter/pull/64

Thank you,
Ronald

**Comment by mankee10200** [comment]
Hi, is there any updates on getting this PR merged? Would be great to have support soon!

**Comment by jonnenauha** [comment]
Merged https://github.com/jonnenauha/prometheus_varnish_exporter/pull/64

**Comment by moon-hawk** [comment]
I can confirm that prometheus_varnish_exporter 1.6.1 is also working with varnish 7.0.3
`
2022/12/02 14:18:24 prometheus_varnish_exporter v1.6.1 (88a7ace) {


2022/12/02 14:18:24 Found varnishstat 7.0.3 6a4c6a5c7e66a664b140278c209f0b18c544cab8
`
(output from -test)
