### ISSUE TITLE
Is this exporter still maintained ?

### ISSUE THREAD

**Issue by tpoindessous** [jonnenauha/prometheus_varnish_exporter#68]
Hi @jonnenauha 

first, thanks for your work ! 

We are using this exporter and we are a little bit concerned by current state of project. Is this project still maintained or do we need to forked it for our needs ? We prefer contributing to upstream project instead of forking them.

Thanks and happy holidays !

**Comment by jonnenauha** [comment]
I don't use Varnish myself anymore at work, so I have not focused on this too much. Life has gotten in the way of maintaining this project, kids, work etc. :)

Here is my todo list, but if you want speedy results perhaps you should fork. I can't promise when I get to these.

* Need to update to latest prometheus client library
* Go throught PRs
* Test with never Varnish versions

Do you need the current PRs to work on new features/fixes in your fork? If that is the case I should go throug them before you start working there, then makes easier to send work back here (if you wish).

**Comment by jonnenauha** [comment]
Some context, I code professionally 7-10 hours a day. Have had hard time finding motivation and time to continue with open source in the evenings and weekends. 

As I don't use this exporter myself anymore (we do use prometheus heavily though) and I don't know how many people really use this exporter out in the world. It's hard to put work into this when I'm not sure if anyone will benefic. I guess there are a few users out there like you :)

**Comment by yann-soubeyrand** [comment]
Hi @jonnenauha, thanks for the work so far!

We're also users of your exporter at @camptocamp. I guess we can participate in the effort to keep this exporter in good shape. To start with, I can confirm that https://github.com/jonnenauha/prometheus_varnish_exporter/pull/64 works with Varnish 6.5.1.

**Comment by jonnenauha** [comment]
Merged https://github.com/jonnenauha/prometheus_varnish_exporter/pull/64

I'm gonna do some other cleanup and make a stable release so you can test it out. Did you have other conserns I should check out?

**Comment by ronaldploeger** [comment]
Thanks for merging #64

We are using your exporter. I can help testing. 

Best, Ronald

**Comment by johanneswuerbach** [comment]
We also use the exporter and I would be happy to help maintaining it.

**Comment by jonnenauha** [comment]
Here you go guys https://github.com/jonnenauha/prometheus_varnish_exporter/releases/tag/1.6
Took me a while to get travis-ci.org -> travis-ci.com porting done. Now has latest go version for the builder and latest prometheus client library, im sure there were tons of bug fixes and stuff in over a year of development. Hopefully nothing breaking.

Happy testing, let me know if there are problems or you need anything else.
